### ISSUE TITLE
README.rst unicode causing problems

### ISSUE THREAD

**Issue by timokau** [fplll/fpylll#121]
https://github.com/fplll/fpylll/pull/62 is back.

The non-ascii name "Jérôme Benoit" seems to be at fault. It is read in `setup.py` as follows:

```
long_description=open('README.rst').read()
```

And apparently python expects `long_description` to be a simple ASCII string. There are multiple possible fixes:

- "fix" the name by replacing it with a ASCII-equivalent. Then we should also set

```
long_description=open('README.rst').read().encode('ascii')
```

to make sure that a new unicode string in the README will be caught in python2 as well as python3 (which does that implicitly).

- ignore ASCII failures with

```
long_description=open('README.rst').read().encode('ascii', 'replace')
```

Or one of the other [error handlers](https://docs.python.org/3/library/codecs.html#error-handlers).

That will result in the name being "J?r?me Benoit".

- write a different long_description instead of importing the README.

Edit: For some reason the `.encode('ascii', 'replace')` option doesnt work: Now python2 complains (despite the `replace`).

**Comment by kiwifb** [comment]
It's funny I didn't have a problem on Gentoo with python3.6. Which python3 was that?

**Comment by timokau** [comment]
[cpython 3.6.5](https://github.com/NixOS/nixpkgs/blob/402a074cfe0d7855261e3dd84c829d8db3ab686e/pkgs/development/interpreters/python/cpython/3.6/default.nix)

It probably depends on how gentoo installs a python package, weather or not `long_description` in `setup.py` gets parsed or not.

**Comment by kiwifb** [comment]
I am surprised because it chocked on the previous instance but it didn't choke on that one. Things could have changed under the hood without me knowing. In any case if you are affected it certainly should be fixed.

**Comment by malb** [comment]
Thanks, I think I'll cut a new release regardless, makes it easier for everyone.

**Comment by timokau** [comment]
Unfortunately 0.4.1dev didn't fix the issue for me, since `python3` defaulted to ascii encoding. Because of that, `open(...).read()` failed:

```
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 221, in <module>
      long_description=readme_to_long_description(),
    File "setup.py", line 205, in readme_to_long_description
      long_description=open('README.rst').read()
    File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8954: ordinal not in range(128)
```

I've created #122 to fix that.
